### ISSUE TITLE
Implement add_sprite, remove_sprite and _spritemap_changed in SpriteManager

### ISSUE THREAD

**Issue by joshua-sterner** [joshua-sterner/pygameOpenGLUtil#1]
Should also write tests for this.

**Comment by LukeJelly** [comment]
@joshua-sterner What is the plan for this one? Should I create an ArrayList or something to store all the sprites in?

**Comment by LukeJelly** [comment]
@joshua-sterner Trying to figure out exactly what your looking for here.
 
Something like this? 

    def add_sprite(self, sprite):
        """adds a Sprite object to this SpriteManager."""
        self.sprites[sprite.spritemap()] = sprite

**Comment by joshua-sterner** [comment]
Mostly, except self.sprites[sprite.spritemap] should be a list since there will typically be more than one sprite using a spritemap.

**Comment by LukeJelly** [comment]
Got it.  There has to be a lot more code there anyway just wanted to see what your thinking as how you want it stored.

**Comment by LukeJelly** [comment]
@joshua-sterner I believe we can close this.  Look over my most recent commits when you get a chance and let me now if anything needs to change before I close this. 
9cc0a89dac3f23c7ffbb6c01d1a91808a4550364
